package io.signals.admin.feeds

import jakarta.persistence.*
import org.springframework.data.jpa.repository.JpaRepository

/**
 * The model schema returned for an endpoint.
 * We persist these, as they're generated by OpenAI
 */
@Entity
data class FeedModelSchema(

    @Column(nullable = false)
    val feedId: String,

    @Column(length = 10_000)
    val yaml: String,

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column
    val id: String? = null,
) {

}

interface FeedModelSchemaRepository : JpaRepository<FeedModelSchema, String> {
    fun deleteAllByFeedId(feedId: String): Int
    fun findByFeedId(feedId: String): FeedModelSchema?
}